export const ENDPOINTS = {
  health: '/health',
  agentStatus: '/api/v1/agent/status',
  agentStart: '/api/v1/agent/start',
  agentStop: '/api/v1/agent/stop',
  agentLogs: '/api/v1/agent/logs',
  agentLogsStream: '/api/v1/agent/logs/stream',
  systemLogsStream: '/api/v1/agent/system_logs/stream',
  contacts: '/api/v1/contacts/',
  contact: (id) => `/api/v1/contacts/${id}`,
  conversations: '/api/v1/conversations/',
  conversation: (id) => `/api/v1/conversations/${id}`,
  conversationSend: (id) => `/api/v1/conversations/${id}/send`,
  conversationProactive: (id) => `/api/v1/conversations/${id}/proactive`,
  contactStartChat: (id) => `/api/v1/contacts/${id}/start_chat`,
  conversationPause: (id) => `/api/v1/conversations/${id}/pause`,
  settings: '/api/v1/settings/',
  whatsappConnect: '/api/v1/auth/whatsapp/connect',
};
